### PR TITLE
STARK: Add range checking in acquiring chapters' titles and subtitles

### LINKED ISSUE #1466: STARK: Setting chapter with "changeChapter" debug command very high (or low) results in weird chapter values
Related to #1456.

There seems to be no checks performed on setting the value of the "setChapter" command – while luckily it doesn't crash the game, setting too high (or too low) value results in wrong values being set, for example bu setting `changeChapter -9999999999` I get the value of -14100565407 (opposite in case of the positive values).

It seems to happen starting at 2^31 so `changeChapter 2147483647` is okay, while `changeChapter 2147483648` overflows the value to -2147483648. Then setting `changeChapter 2147483649` continues to go higher setting it to -2147483647

Setting it to even more extreme value, such as `changeChapter 99999999999999999999` sets the chapter at -1. I didn't tested at which point exactly does it happen.

### PR DESCRIPTION
**Pull request by DouglasLiuGamer**
Fix #1466

### CODE REVIEW

**Comment by orangeforest11** [comment]
Isn't it better to not hardcode the 150 value?

**Comment by DouglasLiuGamer** [comment]
@orangeforest11 The only place I can think of to get the 150 value is through the chapter.ini file. Yet if the number of chapters contained by that file is less than 15, the game will not run (At least this is what the current logic does). Since the game is already fixed, I personally don't see the need to dynamically get the value.

File: engines/stark/console.cpp [hunk 1]
```diff
@@ -588,6 +587,8 @@ bool Console::Cmd_ChangeLocation(int argc, const char **argv) {
 }
 
 bool Console::Cmd_ChangeChapter(int argc, const char **argv) {
+	static const int32 maxChapterValue = 150;
```
Comment (bgK) [inline engines/stark/console.cpp]: Other chapter checks use 999 as the max value. I see no reason to be very restrictive here, console commands are for developers to debug the game.

File: engines/stark/console.cpp [hunk 2]
```diff
@@ -599,12 +600,13 @@ bool Console::Cmd_ChangeChapter(int argc, const char **argv) {
...
 		return true;
 	}
-
-	long value = strtol(argv[1], 0, 10);
-	if (value >= 0 && value <= INT_MAX)
-		StarkGlobal->setCurrentChapter((int32) value);
-	else
-		debugPrintf("Invalid chapter\n");
+	
+	long value = strtol(argv[1], nullptr, 10);
```
Comment (bgK) [inline engines/stark/console.cpp]: Actually the check is not working because `strtol` is not called correctly. I can say `changeChapter chapter1` and get no error.

**Comment by DouglasLiuGamer** [comment]
The branch in this PR was rebased once.

**Comment by DouglasLiuGamer** [comment]
The branch was rebased once.

@bgK If that's the case, I chose to add a checking in `GameChapter` service, so that at least an invalid chapter value will not crash the game.
About the input checking, I think it is kind of meaningless to make it fancy since it is just a debugging tool for developers. Maybe keeping the status quo is enough.

**Comment by bgK** [comment]
Thanks!
